# Generated by Django 3.2.7 on 2021-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_req_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestresult',
            name='pull_request_assignees',
            field=models.CharField(max_length=100, null=True, verbose_name='Assignees (usernames)'),
        ),
        migrations.AlterField(
            model_name='userrequestresult',
            name='pull_request_reviewers',
            field=models.CharField(max_length=100, null=True, verbose_name='Reviewers (usernames)'),
        ),
    ]
